version: "3.9"

services:
  backend:
    image: 831250773388.dkr.ecr.us-east-1.amazonaws.com/career-genai-backend:latest
    container_name: career-genai-backend
    restart: unless-stopped
    env_file:
      - ./env.backend.prod
    ports:
      - "8000:8000"

  frontend:
    image: 831250773388.dkr.ecr.us-east-1.amazonaws.com/career-genai-frontend:latest
    container_name: career-genai-frontend
    restart: unless-stopped
    env_file:
      - ./env.frontend.prod
    ports:
      - "80:3000"
    depends_on:
      - backend
